# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdf_open <- function(path) {
    .Call(`_RMuPdf_pdf_open`, path)
}

mupdf_version <- function() {
    .Call(`_RMuPdf_mupdf_version`)
}

